CREATE TABLE IF NOT EXISTS `atl_optimg_files` (
    `PATH_MD5` CHAR(32) NOT NULL,
    `PATH` TEXT NOT NULL,
    `SIZE_ORIGINAL` INT(11) UNSIGNED NOT NULL,
    `SIZE_COMPRESSED` INT(11) UNSIGNED NOT NULL,
    `MTIME` INT(11) UNSIGNED NOT NULL,
    `WRITE_ERROR` TINYINT(1) NULL DEFAULT 0,
    `ALREADY_PROCESSED_TODAY` CHAR(1) NOT NULL DEFAULT 'N',
    `LAST_COMPRESSED_DATE` DATETIME NOT NULL DEFAULT 0,
    PRIMARY KEY (`PATH_MD5`),
    INDEX `path_md5` (`PATH_MD5`),
    INDEX `already_processed` (`ALREADY_PROCESSED_TODAY`),
    INDEX `size_compressed` (`SIZE_COMPRESSED`)
);

CREATE TABLE IF NOT EXISTS `atl_optipic_tpl` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `IGNORE_THIS_IBLOCK` TINYINT(1) NULL DEFAULT 0,
    `COMPRESS_QUALITY` TINYINT(3) UNSIGNED NULL,
    `MAX_WIDTH` INT(5) UNSIGNED NULL,
    `MAX_HEIGHT` INT(5) UNSIGNED NULL,
    `IGNORE_PREVIEW` TINYINT(1) NULL DEFAULT 0,
    `COMPRESS_QUALITY_PREVIEW` TINYINT(3) NULL DEFAULT 0,
    `MAX_WIDTH_PREVIEW` INT(5) UNSIGNED NULL,
    `MAX_HEIGHT_PREVIEW` INT(5) UNSIGNED NULL,
    `IGNORE_DETAIL` TINYINT(1) NULL DEFAULT 0,
    `COMPRESS_QUALITY_DETAIL` TINYINT(3) NULL DEFAULT 0,
    `MAX_WIDTH_DETAIL` INT(5) UNSIGNED NULL,
    `MAX_HEIGHT_DETAIL` INT(5) UNSIGNED NULL,
    `IGNORE_PROP` TINYINT(1) NULL DEFAULT 0,
    `COMPRESS_QUALITY_PROP` TINYINT(3) NULL DEFAULT 0,
    `MAX_WIDTH_PROP` INT(5) UNSIGNED NULL,
    `MAX_HEIGHT_PROP` INT(5) UNSIGNED NULL,
    PRIMARY KEY (`ID`),
    INDEX `id` (`ID`)
);

CREATE TABLE IF NOT EXISTS `atl_optipic_tpl_to_iblock` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `IBLOCK_ID` TINYINT(3) UNSIGNED NULL,
    `TEMPLATE_ID` TINYINT(3) UNSIGNED NULL,
    PRIMARY KEY (`ID`),
    INDEX `id` (`ID`),
    INDEX `template_id` (`TEMPLATE_ID`),
    INDEX `iblock_id` (`IBLOCK_ID`)
);

